# Файли та папки, які лінтер має ігнорувати
excluded:
  - Pods
  - WeatherBrickTests
  - WeatherBrickUITests
  - build

# Правила, які ми відключаємо (бо вони іноді занадто суворі)
disabled_rules:
  - trailing_whitespace # Дозволяє пробіли в кінці порожніх рядків
  - line_length         # Відключаємо жорстке обмеження на довжину рядка (за замовчуванням 120 символів)
  - force_cast          # Дозволяє використовувати "as!" (хоча це й не дуже безпечно, для навчального проєкту ок)

# Налаштування конкретних правил
opt_in_rules:
  - empty_count         # Рекомендує використовувати .isEmpty замість .count == 0
  - force_unwrapping    # Попереджає про використання "!" (force unwrap)
  - missing_docs # НОВЕ: Вимагає документувати всі публічні декларації

# Кастомні налаштування (наприклад, максимальна кількість рядків у функції)
function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500
