name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select latest Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Build and run XCTests
        run: |
          xcodebuild clean test \
            -scheme "WeatherBrick" \
            -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            ONLY_ACTIVE_ARCH=NO
